"""Regenerate the golden assembly vectors used by the test suite.

``tests/fixtures/assembly_v1_vectors.json`` pins the exact bytes a handful of
scenarios must produce.  It is what catches an accidental change to the
declarative specification, and it is the conformance reference a port of this
project to another language should reproduce byte for byte.

Run it after any deliberate change to the specification, and review the diff:

.. code-block:: shell

    python tools/make_fixtures.py
"""

import argparse
import collections
import dataclasses
import json
import os
import sys
from typing import Any, Dict, List, Optional

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from mecademic_fieldbus import get_io_map  # noqa: E402
from mecademic_fieldbus.io_map.base import IoMap  # noqa: E402
from mecademic_fieldbus.robot_classes import (  # noqa: E402
    InverseKinematicsConfiguration,
    MotionCommand,
    MotionControl,
    MotionStatus,
    RobotControl,
    RobotPosition,
    RobotSafetyStatus,
    RobotStatus,
    SafetyStopFlags,
)
from mock_robot.simulator import DEFAULT_FIFO_SPACE, DEMO_MOTION_COMMAND_IDS  # noqa: E402

#: Where the vectors are written, relative to the repository root.
DEFAULT_OUTPUT = os.path.join("tests", "fixtures", "assembly_v1_vectors.json")

#: Header explaining to a reader what the file is and when it may change.
COMMENT = (
    "Golden assembly images for io_map version 1, generated by tools/make_fixtures.py "
    "from mecademic_fieldbus/io_map/spec/assembly_v1.json (itself generated from the "
    "official Meca500 EDS). They must only change when that specification changes on "
    "purpose. A port of this project to another language should reproduce these bytes "
    "exactly. See tests/test_io_map.py."
)


def as_json(value: Any) -> Any:
    """Convert a dataclass into JSON-friendly plain data.

    Args:
        value: Dataclass instance to convert.

    Returns:
        Nested dictionaries, lists and scalars.
    """
    return json.loads(json.dumps(dataclasses.asdict(value), default=int))


def input_case(
    io_map: IoMap,
    name: str,
    description: str,
    status: RobotStatus,
    motion_status: MotionStatus,
    safety_status: RobotSafetyStatus,
    position: RobotPosition,
) -> Dict[str, Any]:
    """Build one input assembly vector.

    Args:
        io_map: Map used to encode the image.
        name: Short identifier of the scenario.
        description: What the scenario represents.
        status: Robot status to encode.
        motion_status: Motion status to encode.
        safety_status: Safety status to encode.
        position: Position feedback to encode.

    Returns:
        The vector, ready to be serialised.
    """
    raw = io_map.empty_input_assembly()
    raw = io_map.encode_status(status, raw)
    raw = io_map.encode_motion_status(motion_status, raw)
    raw = io_map.encode_safety_status(safety_status, raw)
    raw = io_map.encode_position(position, raw)
    return collections.OrderedDict(
        [
            ("name", name),
            ("description", description),
            ("hex", raw.hex()),
            ("status", as_json(status)),
            ("motion_status", as_json(motion_status)),
            ("safety_status", as_json(safety_status)),
            ("position", as_json(position)),
        ]
    )


def output_case(
    io_map: IoMap,
    name: str,
    description: str,
    robot_control: RobotControl,
    motion_control: MotionControl,
    motion_command: MotionCommand,
) -> Dict[str, Any]:
    """Build one output assembly vector.

    Args:
        io_map: Map used to encode the image.
        name: Short identifier of the scenario.
        description: What the scenario represents.
        robot_control: Robot control bits to encode.
        motion_control: Motion control bits to encode.
        motion_command: Motion command to encode.

    Returns:
        The vector, ready to be serialised.
    """
    raw = io_map.empty_output_assembly()
    raw = io_map.encode_robot_control(robot_control, raw)
    raw = io_map.encode_motion_control(motion_control, raw)
    raw = io_map.encode_motion_command(motion_command, raw)
    return collections.OrderedDict(
        [
            ("name", name),
            ("description", description),
            ("hex", raw.hex()),
            ("robot_control", as_json(robot_control)),
            ("motion_control", as_json(motion_control)),
            ("motion_command", as_json(motion_command)),
        ]
    )


def build_document(io_map: IoMap) -> Dict[str, Any]:
    """Build the complete vector document.

    Args:
        io_map: Map the vectors are generated for.

    Returns:
        The document, ready to be serialised.
    """
    zero_position = RobotPosition(joints=(0.0,) * 6, pose=(0.0,) * 6)
    home_position = RobotPosition(
        joints=(0.0, 10.5, -20.25, 0.0, 90.0, -45.0),
        pose=(100.0, 71.0, 159.5, 0.0, 90.0, -45.0),
        shoulder=InverseKinematicsConfiguration.POSITIVE,
        elbow=InverseKinematicsConfiguration.POSITIVE,
        wrist=InverseKinematicsConfiguration.NEGATIVE,
        turn=InverseKinematicsConfiguration.UNDEFINED,
    )
    idle_motion = MotionStatus(
        end_of_block=True, end_of_movement=True, fifo_space=DEFAULT_FIFO_SPACE
    )
    powered_safety = RobotSafetyStatus(motor_voltage_on=True)

    return collections.OrderedDict(
        [
            ("comment", COMMENT),
            ("assembly_version", io_map.version),
            (
                "input",
                [
                    input_case(
                        io_map,
                        "deactivated",
                        "Robot powered down, brakes engaged, no error.",
                        RobotStatus(brakes_engaged=True),
                        idle_motion,
                        RobotSafetyStatus(),
                        zero_position,
                    ),
                    input_case(
                        io_map,
                        "homed_idle",
                        "Robot activated, homed and idle after move 7.",
                        RobotStatus(activated=True, homed=True),
                        dataclasses.replace(idle_motion, move_id=7, reached_checkpoint_id=3),
                        powered_safety,
                        home_position,
                    ),
                    input_case(
                        io_map,
                        "moving",
                        "Robot executing move 8.",
                        RobotStatus(activated=True, homed=True),
                        MotionStatus(move_id=8, fifo_space=DEFAULT_FIFO_SPACE - 1),
                        powered_safety,
                        RobotPosition(
                            joints=(5.0, 0.0, 0.0, 0.0, 45.0, 0.0),
                            pose=(110.0, 50.0, 200.0, 0.0, 45.0, 0.0),
                            shoulder=InverseKinematicsConfiguration.POSITIVE,
                            elbow=InverseKinematicsConfiguration.POSITIVE,
                            wrist=InverseKinematicsConfiguration.POSITIVE,
                            turn=InverseKinematicsConfiguration.POSITIVE,
                        ),
                    ),
                    input_case(
                        io_map,
                        "estop",
                        "Emergency stop asserted, robot in error and paused.",
                        RobotStatus(activated=True, homed=True, error_code=3005),
                        dataclasses.replace(idle_motion, paused=True, move_id=8),
                        RobotSafetyStatus(
                            stops=SafetyStopFlags(estop=True),
                            resettable_stops=SafetyStopFlags(estop=True),
                            reset_ready=True,
                            motor_voltage_on=False,
                        ),
                        home_position,
                    ),
                    input_case(
                        io_map,
                        "busy_homing",
                        "Robot activated and running its homing sequence.",
                        RobotStatus(busy=True, activated=True),
                        idle_motion,
                        powered_safety,
                        zero_position,
                    ),
                ],
            ),
            (
                "output",
                [
                    output_case(
                        io_map,
                        "idle",
                        "Nothing requested.",
                        RobotControl(),
                        MotionControl(),
                        MotionCommand.none(),
                    ),
                    output_case(
                        io_map,
                        "activate",
                        "Activation requested.",
                        RobotControl(activate=True),
                        MotionControl(),
                        MotionCommand.none(),
                    ),
                    output_case(
                        io_map,
                        "home",
                        "Activation and homing requested.",
                        RobotControl(activate=True, home=True),
                        MotionControl(),
                        MotionCommand.none(),
                    ),
                    output_case(
                        io_map,
                        "deactivate",
                        "Deactivation requested; it takes precedence over activation.",
                        RobotControl(deactivate=True),
                        MotionControl(),
                        MotionCommand.none(),
                    ),
                    output_case(
                        io_map,
                        "reset_error",
                        "Error reset requested.",
                        RobotControl(reset_error=True),
                        MotionControl(),
                        MotionCommand.none(),
                    ),
                    output_case(
                        io_map,
                        "move_joints",
                        "Joint move 3, using the synthetic command id of the simulator.",
                        RobotControl(activate=True),
                        MotionControl(move_id=3, setpoint=True),
                        MotionCommand.build(
                            DEMO_MOTION_COMMAND_IDS["MoveJoints"],
                            (0.0, 10.5, -20.25, 0.0, 90.0, -45.0),
                        ),
                    ),
                    output_case(
                        io_map,
                        "resume_motion",
                        "Motion resumed after a pause; this bit acts on its rising edge.",
                        RobotControl(activate=True),
                        MotionControl(move_id=3, resume_motion=True),
                        MotionCommand.none(),
                    ),
                ],
            ),
        ]
    )


def main(argv: Optional[List[str]] = None) -> int:
    """Regenerate the golden vectors.

    Args:
        argv: Command line arguments, defaulting to ``sys.argv[1:]``.

    Returns:
        The process exit code.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--output", "-o", default=DEFAULT_OUTPUT, help="file to write (default: %(default)s)"
    )
    args = parser.parse_args(argv)

    io_map = get_io_map()
    document = build_document(io_map)
    with open(args.output, "w") as handle:
        json.dump(document, handle, indent=2)
        handle.write("\n")
    print(
        "wrote {} ({} input and {} output vectors for assembly version {})".format(
            args.output, len(document["input"]), len(document["output"]), io_map.version
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
